In [10]:

function generate_reflections(hmax,nth)
    sc  = Dict{Int, Vector{Tuple{Int,Int,Int}}}()
    bcc = Dict{Int, Vector{Tuple{Int,Int,Int}}}()
    fcc = Dict{Int, Vector{Tuple{Int,Int,Int}}}()

    for h in 0:hmax, k in 0:hmax, l in 0:hmax

        N = h^2 + k^2 + l^2
        hkl = (h,k,l)

        # --- SC: alle erlaubten Reflexe ---
        if length(sc) == nth
            if N < maximum(keys(sc))
                delete!(sc, maximum(keys(sc)))
            end
        end 

        if length(fcc) == nth
            if N < maximum(keys(fcc))
                delete!(fcc, maximum(keys(fcc)))
            end
        end 

        if length(bcc) == nth
            if N < maximum(keys(bcc))
                delete!(bcc, maximum(keys(bcc)))
            end
        end 


        if length(sc) < nth
            push!(get!(sc, N, Vector{Tuple{Int,Int,Int}}()), hkl)
        end

        # --- BCC: h+k+l gerade ---
        if length(bcc) < nth
            if (h + k + l) % 2 == 0
                push!(get!(bcc, N, Vector{Tuple{Int,Int,Int}}()), hkl) 
            end
        end

        # --- FCC: alle h,k,l entweder alle gerade oder alle ungerade ---
        if length(fcc) < nth
            if (h % 2 == k % 2 == l % 2)
                push!(get!(fcc, N, Vector{Tuple{Int,Int,Int}}()), hkl)
            end
        end
    end
    sc_sorted = [(N, sc[N]) for N in sort(collect(keys(sc)))]
    bcc_sorted = [(N, bcc[N]) for N in sort(collect(keys(bcc)))]
    fcc_sorted = [(N, fcc[N]) for N in sort(collect(keys(fcc)))]
    return sc_sorted, bcc_sorted, fcc_sorted
end


generate_reflections (generic function with 1 method)

In [11]:
function anglestheo(n)
    rfl=generate_reflections(n,n)[3]
    println(rfl)
    α = zeros(n)
    for i in 1:n
        if rfl[i][2][1] == (0,0,0) 
        α[i] = 0
        print("hi")
        else
        α[i] = acos((rfl[i][2][1][1]+rfl[i][2][1][2]+rfl[i][2][1][3])/(sqrt(3)* sqrt((rfl[i][2][1][1]^2+rfl[i][2][1][2]^2+rfl[i][2][1][3]^2)))-0.00000000002)/pi*180
        end
    end
return α
end
#also ich berechne hier einfach nur die winkel zwischen ebenen mit millerindizes. das entspricht den winkeln ihrer normalen also der rez. gittervektoren
# wegen kubischen gitter kann ich einfaches SP benutzen
#
#dannach schaue ich mir die gemessenen reflexe an und kriege damit die richtung von k´(ich sage k, k´haben selben betrag). aus k-k´kann ich die richtung von g berechnen.
#mit diesem g kann ich dann den winkel zu k berechnen, wobei k parallel zu 1 1 1 ist und die reflexe zuordnen. ich kann nur die wiunkel zwischen k und deltak berechnen
#aber ich kann nicht die richtung von deltak im gitterkoordinatensystem bestimmen, darum das winkelgerechne

anglestheo (generic function with 1 method)

In [12]:
using LinearAlgebra

In [24]:
function anglesprax(th, ph,th111,ph111)
    th = th .* pi/180
    ph = ph .* pi/180
    kk(x,y)=[(sin(x)*cos(y))';
     (sin(x).*sin(y))';
      (cos(x)')]
    #println(kk.(th,ph))
    kkvec=kk.(th,ph)
    kvec = kk(th111*pi/180, ph111*pi/180)
    g = zeros(3,length(th))
    #println(g)
    h= zeros(length(th))
    kg=(kvec-[0,0,-1])/norm(kvec-[0,0,-1])
    for i in 1:length(th)
        #println(kvec)
        g[:, i] =  kkvec[i]-[0,0,-1]
        #println(g[:, i])
        g[:, i]=g[:, i]/norm(g[:, i])
        h[i] = acos(kg' *g[:, i])/pi*180
    end
    return h
end

anglesprax (generic function with 2 methods)

In [25]:
th, ph = [0.0, 90, 60], [0.0, 0, 60]
anglesprax(th, ph, -13, 15)


3-element Vector{Float64}:
  6.50000000000002
 51.30003615638831
 34.87162858219098

In [26]:
[1 0 0] - [2 3 4]

1×3 Matrix{Int64}:
 -1  -3  -4

In [35]:
ph = -1 .*[5.5, 2, -8, 10, 6.5, 2, -4, -13, -25, 20.5, 8, -6.5, -5.5, -16, -18]
th = [28, 26, 26, 18, 17.5, 16.5, 16, 15, 13.5, 8, 6.5, 7, 6, 6, 1.5]


15-element Vector{Float64}:
 28.0
 26.0
 26.0
 18.0
 17.5
 16.5
 16.0
 15.0
 13.5
  8.0
  6.5
  7.0
  6.0
  6.0
  1.5

In [36]:
anglesprax([-13],[15], -13, 15)

1-element Vector{Float64}:
 0.0

In [37]:
generate_reflections(14,14) 

([(0, [(0, 0, 0)]), (1, [(0, 0, 1), (0, 1, 0), (1, 0, 0)]), (2, [(0, 1, 1), (1, 0, 1), (1, 1, 0)]), (3, [(1, 1, 1)]), (4, [(0, 0, 2), (0, 2, 0), (2, 0, 0)]), (5, [(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]), (6, [(1, 1, 2), (1, 2, 1), (2, 1, 1)]), (8, [(0, 2, 2), (2, 0, 2), (2, 2, 0)]), (9, [(0, 0, 3), (0, 3, 0), (1, 2, 2), (2, 1, 2), (2, 2, 1), (3, 0, 0)]), (10, [(0, 1, 3), (0, 3, 1), (1, 0, 3), (1, 3, 0), (3, 0, 1), (3, 1, 0)]), (11, [(1, 1, 3), (1, 3, 1), (3, 1, 1)]), (12, [(2, 2, 2)]), (13, [(0, 2, 3), (0, 3, 2), (2, 0, 3), (2, 3, 0), (3, 0, 2), (3, 2, 0)]), (14, [(3, 2, 1)])], [(0, [(0, 0, 0)]), (2, [(0, 1, 1), (1, 0, 1), (1, 1, 0)]), (4, [(0, 0, 2), (0, 2, 0), (2, 0, 0)]), (6, [(1, 1, 2), (1, 2, 1), (2, 1, 1)]), (8, [(0, 2, 2), (2, 0, 2), (2, 2, 0)]), (10, [(0, 1, 3), (0, 3, 1), (1, 0, 3), (1, 3, 0), (3, 0, 1), (3, 1, 0)]), (12, [(2, 2, 2)]), (14, [(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]), (16, [(0, 0, 4), (0, 4, 0), (4, 0, 0)]), (

In [38]:
anglesprax(ph, th, 13, 15)

15-element Vector{Float64}:
  9.200249132102705
  7.484049503754279
  2.6838199675003542
 11.496113465569444
  9.747933160687206
  7.499702812836956
  4.500439389637866
  0.0
  6.00460044848175
 16.72012332687271
 10.472694034541584
  3.312521239627887
  3.8081292275942142
  1.8771539874916012
  3.0763325869867666